import React from "react";
import {
  Code2,
  Globe,
  Smartphone,
  PenTool,
  Cloud,
  BrainCircuit,
  Target,
  Cpu,
  Layers,
  ShieldCheck,
  RefreshCw,
  Handshake,
  CheckCircle2,
  Sparkles,
  ArrowRight,
  Quote,
  Crosshair,
  Telescope,
  Lightbulb,
  Shield,
  Gem,
  Users,
  Flag,
  Trophy,
  Dot,
  PlugZap,
  LifeBuoy,
  ChevronDown,
  ChevronRight,
  TrendingUp,
  Search,
  FileText,
  Mail,
  Phone,
  MapPin,
  Clock,
  Linkedin,
  Twitter,
  Github,
  Instagram,
  Menu,
  X,
  Check,
  AlertCircle,
  LucideProps,
} from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  "code-2": Code2,
  code: Code2,
  globe: Globe,
  smartphone: Smartphone,
  "pen-tool": PenTool,
  cloud: Cloud,
  "brain-circuit": BrainCircuit,
  target: Target,
  cpu: Cpu,
  layers: Layers,
  "shield-check": ShieldCheck,
  "refresh-cw": RefreshCw,
  handshake: Handshake,
  "check-circle-2": CheckCircle2,
  sparkles: Sparkles,
  "arrow-right": ArrowRight,
  quote: Quote,
  crosshair: Crosshair,
  telescope: Telescope,
  lightbulb: Lightbulb,
  shield: Shield,
  gem: Gem,
  users: Users,
  flag: Flag,
  trophy: Trophy,
  dot: Dot,
  "plug-zap": PlugZap,
  "life-buoy": LifeBuoy,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "trending-up": TrendingUp,
  search: Search,
  "file-text": FileText,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  clock: Clock,
  linkedin: Linkedin,
  twitter: Twitter,
  github: Github,
  instagram: Instagram,
  menu: Menu,
  x: X,
  check: Check,
  "alert-circle": AlertCircle,
};

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, className = "w-5 h-5", ...props }: IconProps) {
  const Component = ICON_MAP[name] || Sparkles;
  return <Component className={className} {...props} />;
}
